version: 2

# Build configuration
build:
  os: ubuntu-20.04  # Specify the OS for the build environment
  tools:
    java: "openjdk-17"  # Specify the Java version
    maven: "4.0.0"  # Specify the Maven version

# Documentation versions
versions:
  latest:
    name: Latest
    identifier: main
    default: true

# Dependencies and build instructions
java:
  version: "openjdk-17"
  install:
    - requirements: requirements.txt

# Build commands for the Java project
commands:
  - mvn package  # Assuming Maven is used to build the project
  - mkdocs build
