version: 2

# Build configuration
build:
  image: latest

# Documentation versions
versions:
  latest:
    name: Latest
    identifier: main
    default: true

# Build instructions
python:
  version: 3.8
  install:
    - requirements: requirements.txt
  script:
    - mvn package  # Assuming Maven is used to build the JavaFX project
    - mkdocs build
