version: 2

# Build configuration with necessary tools and commands
build:
  tools:
    python: "3.8"  # Specify the Python version for MkDocs

# Documentation versions
versions:
  latest:
    name: Latest
    identifier: main
    default: true

# Dependencies and build instructions
python:
  install:
    - requirements: requirements.txt

# Build commands for the Java project
build:
  commands:
    - apt-get update && apt-get install -y openjdk-11-jdk maven  # Install Java and Maven
    - mvn package  # Assuming Maven is used to build the project
    - mkdocs build  # Build the documentation using MkDocs
